name: Publish PyPI

on:
  push:
    branches:
      - main

jobs:
  pypi:
    name: Release To PyPI
    runs-on: [ubuntu-latest, macos-13, windows-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: Install publishing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        pyproject-build --outdir dist .
        twine upload dist/*
